### ISSUE TITLE
Mandatory parameters for openntp class

### ISSUE THREAD

**Issue by vincentbernat** [tohuwabohu/puppet-openntp#3]
Hey!

Documentation says that we should be able to do `class { openntp: }` and that's all. However, this class has many mandatory parameters. They are provided in `data`, but with Puppet 3.8 and hiera 1.3, they are not used.

**Comment by tohuwabohu** [comment]
This issue can only happen when the mandatory Puppet module `ripienaar/module_data` is not installed (and hence the configuration in `data` is ignored). Is the module installed?

**Comment by vincentbernat** [comment]
Yes, it's installed. Does it have to be enabled in some way?

**Comment by vincentbernat** [comment]
OK, Puppet needs to be restarted after installing the `module_data` module. It works just fine now.

**Comment by tohuwabohu** [comment]
Ah, good to know.
